import { bgs } from './items';
import { items } from './items';

// 樵夫列表
export const QiaoFuList = [
  {
    id: 1,
    name: '青皮柳',
    cd: 2,
    quality: 1,
    growthArea: '各大城镇河畔',
    description: '垂丝如瀑，树皮泛青',
    xp: 1,
    img: bgs.青皮柳,
    itemImg: items.青皮柳,
  },
  {
    id: 2,
    name: '铁杉木',
    cd: 3,
    quality: 2,
    growthArea: '门派后山',
    description: '树干笔直似剑，叶如钢针',
    xp: 2,
    img: bgs.铁杉木,
    itemImg: items.铁杉木,
  },
  {
    id: 3,
    name: '醉仙桃',
    cd: 4,
    quality: 3,
    growthArea: '酒肆周边',
    description: '桃胶散发酒香，花瓣粉中透红',
    xp: 3,
    img: bgs.醉仙桃,
    itemImg: items.醉仙桃,
  },
  {
    id: 4,
    name: '八卦竹',
    cd: 5,
    quality: 4,
    growthArea: '道观阵法中',
    description: '竹节天然形成八卦纹路',
    xp: 4,
    img: bgs.八卦竹,
    itemImg: items.八卦竹,
  },
  {
    id: 5,
    name: '寒潭柏',
    cd: 6,
    quality: 5,
    growthArea: '雪山寒潭边',
    description: '树冠积雪，木质透蓝',
    xp: 6,
    img: bgs.寒潭柏,
    itemImg: items.寒潭柏,
  },
  {
    id: 6,
    name: '金丝楠',
    cd: 7,
    quality: 6,
    growthArea: '帝王陵墓区',
    description: '木纹流淌金色脉络',
    xp: 9,
    img: bgs.金丝楠,
    itemImg: items.金丝楠,
  },
  {
    id: 7,
    name: '血枫木',
    cd: 8,
    quality: 7,
    growthArea: '古战场遗址',
    description: '红叶滴血，树根缠绕残剑',
    xp: 12,
    img: bgs.血枫木,
    itemImg: items.血枫木,
  },
  {
    id: 8,
    name: '玉菩提',
    cd: 9,
    quality: 8,
    growthArea: '佛门禁地',
    description: '菩提树下，玉石般晶莹',
    xp: 20,
    img: bgs.玉菩提,
    itemImg: items.玉菩提,
  },
  {
    id: 9,
    name: '幽冥槐',
    cd: 10,
    quality: 9,
    growthArea: '阴阳交界处',
    description: '半枯半荣，树洞传出哭声',
    xp: 30,
    img: bgs.幽冥槐,
    itemImg: items.幽冥槐,
  },
  {
    id: 10,
    name: '龙血木',
    cd: 20,
    quality: 10,
    growthArea: '云海浮岛（轻功挑战）',
    description: '树皮如龙鳞，树脂似熔岩',
    xp: 40,
    img: bgs.龙血木,
    itemImg: items.龙血木,
  },
];
